### PR TITLE
Updates pattern contents

### PR DESCRIPTION
**Pull request by allanlasser**
- Removes Shopify product data but retains Look data for bootstrapping excellence.
- Updates schema without any Shopify secrets for security supremacy.
- Adds pattern metadata to pretty up the deploy process.

Try deploying this new pattern in production: https://app.takeshape.io/add-to-takeshape?repo=https://github.com/takeshape/takeshape-starter-shopify-nextjs/tree/update-pattern/.takeshape/pattern

### CODE REVIEW

**Comment by mcat** [comment]
Looks like we're still running into the migration issue here.

**Comment by allanlasser** [comment]
Hmm, I'd like to tag @incompl in to review the `schema.json`. Not sure why the migration issue is popping up, but I saw the same thing.

**Comment by mcat** [comment]
> Hmm, I'd like to tag @incompl in to review the `schema.json`. Not sure why the migration issue is popping up, but I saw the same thing.

Also worth asking @incompl about which of these properties are actually required in the schema:

```
"services": {
  "shopify:takeshape-io-shop": {
    "params": {
      "type": "graphql",
      "namespace": "NNN",
      "shop": "NNN",
      "authHeader": "X-Shopify-Access-Token",
      "endpoint": "NNN",
      "name": "Shopify Lookbook"
    }
  }
}
```

**Comment by incompl** [comment]
It looks like all these fields do get created in the latest code, so I'd update these to be correct. Here is a working example:

```json
{
   "services":{
      "shopify:gregs-takeshape-store":{
         "params":{
            "type":"graphql",
            "namespace":"Shopify",
            "shop":"gregs-takeshape-store",
            "authHeader":"X-Shopify-Access-Token",
            "endpoint":"https://gregs-takeshape-store.myshopify.com/admin/api/2020-07/graphql.json",
            "name":"Whatever you want to name it goes here"
         }
      }
   }
}
```

**Pull request merged**
